export const SET_EVENTS = "SET_EVENTS";
export const SET_EVENTS_ERROR = "SET_EVENTS_ERROR";
export const SET_EVENTS_CURRENT_STATE = "SET_EVENTS_CURRENT_STATE";
export const SET_EVENTS_SELECTED_OBJECT = "SET_EVENTS_SELECTED_OBJECT";

export const SET_CONTACTS = "SET_CONTACTS";
export const SET_CONTACTS_ERROR = "SET_CONTACTS_ERROR";
export const SET_CONTACTS_CURRENT_STATE = "SET_CONTACTS_CURRENT_STATE";
export const SET_CONTACTS_SELECTED_OBJECT = "SET_CONTACTS_SELECTED_OBJECT";
