export const SET_EVENTS = "SET_EVENTS";
export const SET_EVENTS_ERROR = "SET_EVENTS_ERROR";
export const SET_EVENTS_CURRENT_STATE = "SET_EVENTS_CURRENT_STATE";
export const SET_EVENTS_SELECTED_OBJECT = "SET_EVENTS_SELECTED_OBJECT";

export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const SET_APPOINTMENTS_ERROR = "SET_APPOINTMENTS_ERROR";
export const SET_APPOINTMENTS_CURRENT_STATE = "SET_APPOINTMENTS_CURRENT_STATE";
export const SET_APPOINTMENTS_CLEAR = "SET_APPOINTMENTS_CLEAR";

export const SET_CONTACTS = "SET_CONTACTS";
export const SET_CONTACTS_ERROR = "SET_CONTACTS_ERROR";
export const SET_CONTACTS_CURRENT_STATE = "SET_CONTACTS_CURRENT_STATE";

export const SET_GROUPS = "SET_GROUPS";
export const SET_GROUPS_ERROR = "SET_GROUPS_ERROR";
export const SET_GROUPS_CURRENT_STATE = "SET_GROUPS_CURRENT_STATE";
export const SET_GROUPS_SELECTED_OBJECT = "SET_GROUPS_SELECTED_OBJECT";
